services:
  - type: web
    name: audio-converter
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn transformar:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
